server:
  port: 9200

spring:
  application:
    name: theme-service
  config:
    import: "configserver:http://localhost:9002/"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
