server:
  port: 9300

spring:
  application:
    name: article-service
  config:
    import: "configserver:http://localhost:9002/"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
